# Generated by Django 5.0 on 2024-10-08 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('emergency_contact', models.CharField(max_length=10)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('daibitic', models.BooleanField()),
                ('blood_grp', models.CharField(choices=[('a+', 'A+'), ('b+', 'B+'), ('a-', 'A-'), ('b-', 'B-'), ('ab-', 'AB-'), ('o-', 'O-'), ('ab+', 'AB+'), ('o+', 'O+')], max_length=3)),
                ('allergy', models.CharField(max_length=20)),
                ('med_issue', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('maxcare_patient.myuser',),
        ),
    ]
