# Generated by Django 5.0 on 2024-10-08 13:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('degree', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('doc_img', models.ImageField(max_length=500, upload_to='doctors')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('maxcare_patient.myuser',),
        ),
    ]
