# Generated by Django 5.0 on 2024-10-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0003_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='daibitic',
            field=models.BooleanField(default=False),
        ),
    ]
