# Generated by Django 5.0 on 2024-10-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0004_alter_patient_daibitic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='marital_status',
            field=models.CharField(choices=[('UM', 'Unmarrid'), ('MA', 'Married')], default='UM', max_length=2),
        ),
    ]
