# Generated by Django 5.0 on 2024-10-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0005_alter_myuser_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='daibitic',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
