# Generated by Django 5.0 on 2024-10-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0006_alter_patient_daibitic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergy',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
