# Generated by Django 5.0 on 2024-10-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0007_alter_patient_allergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='med_issue',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
