# Generated by Django 5.0 on 2024-10-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0009_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_fee',
            field=models.IntegerField(default=2000),
        ),
    ]
