# Generated by Django 5.0 on 2024-10-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0010_doctor_doc_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_date',
            field=models.DateField(null=True),
        ),
    ]
