# Generated by Django 5.0 on 2024-10-11 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0011_alter_appointments_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
