# Generated by Django 5.0 on 2024-10-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0013_appointments_admin_approval_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=15)),
                ('priority', models.IntegerField(unique=True)),
                ('admin_visibility', models.BooleanField(default=1)),
                ('doctor_visibility', models.BooleanField(default=0)),
                ('patient_visibility', models.BooleanField(default=0)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
    ]
