# Generated by Django 5.0 on 2024-10-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0015_alter_sidebar_unique_together_sidebar_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='url',
            field=models.CharField(max_length=25),
        ),
    ]
