# Generated by Django 5.0 on 2024-10-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0016_alter_sidebar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
