# Generated by Django 5.0 on 2024-10-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0017_alter_sidebar_icon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sidebar',
            unique_together={('visibility', 'priority')},
        ),
    ]
