# Generated by Django 5.0 on 2024-10-11 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0018_alter_sidebar_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='appointment_date',
        ),
    ]
