# Generated by Django 5.0 on 2024-10-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0019_remove_appointments_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REQUEST INITIATED', 'Request initiated'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PND', max_length=20),
        ),
    ]
