# Generated by Django 5.0 on 2024-10-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0020_alter_appointments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='btn_class',
            field=models.CharField(default='d-none', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Request Initiated', 'REQUEST INITIATED'), ('Confirmed', 'CONFIRMED'), ('Rejected', 'REJECTED')], default='PND', max_length=20),
        ),
    ]
