# Generated by Django 5.0 on 2024-10-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0021_appointments_btn_class_alter_appointments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Request Initiated', 'REQUEST INITIATED'), ('Confirmed', 'CONFIRMED'), ('Rejected', 'REJECTED')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='type',
            field=models.CharField(choices=[('PATIENT', 'patient'), ('DOCTOR', 'doctor'), ('RECEPTIONIST', 'receptionist')], default='PATIENT', max_length=15),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='visibility',
            field=models.CharField(choices=[('PATIENT', 'patient'), ('DOCTOR', 'doctor'), ('RECEPTIONIST', 'receptionist')], default='RECEPTIONIST', max_length=15),
        ),
    ]
