# Generated by Django 5.0 on 2024-10-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0023_alter_sidebar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='rejection_remark',
            field=models.TextField(max_length=510, null=True),
        ),
    ]
