# Generated by Django 5.0 on 2024-10-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0028_alter_appointments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='prescribed_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
