# Generated by Django 5.0 on 2024-10-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0029_appointments_prescribed_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='marital_status',
            field=models.CharField(choices=[('UM', 'Unmarrid'), ('MA', 'Married'), ('W', 'Widowed')], default='UM', max_length=2),
        ),
    ]
