# Generated by Django 5.0 on 2024-10-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0030_alter_myuser_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
    ]
