# Generated by Django 5.0 on 2024-10-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0032_alter_myuser_pincode_alter_patient_blood_grp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='daibitic',
            new_name='is_daibitic',
        ),
    ]
