# Generated by Django 5.0 on 2024-10-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0033_rename_daibitic_patient_is_daibitic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergy',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
