# Generated by Django 5.0 on 2024-11-05 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0036_patient_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=models.CharField(choices=[('MBBS', 'Bachelor of Medicine, Bachelor of Surgery'), ('BDS', 'Bachelor of Dental Surgery'), ('BAMS', 'Bachelor of Ayurvedic Medicine and Surgery'), ('BUMS', 'Bachelor of Unani Medicine and Surgery'), ('BHMS', 'Bachelor of Homeopathy Medicine and Surgery'), ('BYNS', 'Bachelor of Yoga and Naturopathy Sciences'), ('B.V.Sc & AH', 'Bachelor of Veterinary Sciences and Animal Husbandry')], max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='maxcare_patient.specialization'),
        ),
    ]
