# Generated by Django 5.0 on 2024-11-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxcare_patient', '0038_remove_doctor_degree_specialization_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='btn_class',
        ),
    ]
